version: 2.1

orbs:
  # This uses the Orbs located at https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@0.0.27

jobs:
  Test:
    macos:
      xcode: 11.2.1
    steps:
      - checkout
      - run:
          name: Copy Demo SPCredentials
          command: mkdir -p Simplenote/Credentials && cp Simplenote/SPCredentials-demo.swift Simplenote/Credentials/SPCredentials.swift
      - macos/install-dependencies:
          bundle-install: true
          pod-install: true
      - macos/test:
          name: Build
          workspace: Simplenote.xcworkspace
          scheme: Simplenote

workflows:
  simplenote_macos:
    jobs:
      - Test
